export const DEFAULT_ACTION = 'app/USER_MANAGEMENT/LIST_USERS/DEFAULT_ACTION';
export const DISPLAY_WARNING_ACTION = 'app/USER_MANAGEMENT/LIST_USERS/DISPLAY_WARNING_ACTION';
export const MOVE_TO_URL_ACTION = 'app/USER_MANAGEMENT/LIST_USERS/MOVE_TO_URL_ACTION';

export const HANDLE_ITEM_CHANGE_ACTION = 'app/USER_MANAGEMENT/LIST_USERS/HANDLE_ITEM_CHANGE_ACTION';
export const RECEIVED_USER_LIST_DATA_ERROR = 'app/USER_MANAGEMENT/LIST_USERS/RECEIVED_USER_LIST_DATA_ERROR';
export const RECEIVED_USER_LIST_DATA_ACTION = 'app/USER_MANAGEMENT/LIST_USERS/RECEIVED_USER_LIST_DATA_ACTION';
export const RECEIVED_MERCHANT_USER_LIST_DATA_ACTION = 'app/USER_MANAGEMENT/LIST_USERS/RECEIVED_MERCHANT_USER_LIST_DATA_ACTION';
export const VIEW_USER_ACTION  = 'app/USER_MANAGEMENT/LIST_USERS/VIEW_USER_ACTION';

export const GET_USER_LIST_DATA = 'app/USER_MANAGEMENT/LIST_USERS/GET_USER_LIST_DATA';
export const GET_MERCHANT_USER_LIST_DATA = 'app/USER_MANAGEMENT/LIST_USERS/GET_MERCHANT_USER_LIST_DATA';
export const CHANGE_MERCHANT_USERS_PAGE_ACTION = 'app/USER_MANAGEMENT/LIST_USERS/CHANGE_MERCHANT_USERS_PAGE_ACTION';

export const ADD_USER_ACTION = 'app/USER_MANAGEMENT/LIST_USERS/ADD_USER_ACTION';
export const WARNING_BACK_ACTION = 'app/USER_MANAGEMENT/LIST_USERS/WARNING_BACK_ACTION';