export const DEFAULT_ACTION = 'app/USER_MANAGEMENT/SECURITY_LOG/DEFAULT_ACTION';
export const GET_SECURITY_LOGS_DATA = 'app/USER_MANAGEMENT/SECURITY_LOG/GET_SECURITY_LOGS_DATA';
export const MOVE_TO_URL_ACTION = 'app/USER_MANAGEMENT/SECURITY_LOG/MOVE_TO_URL_ACTION';

export const HANDLE_ITEM_CHANGE_ACTION = 'app/USER_MANAGEMENT/SECURITY_LOG/HANDLE_ITEM_CHANGE_ACTION';
export const RECEIVED_SECURITY_LOG_DATA_ERROR = 'app/USER_MANAGEMENT/SECURITY_LOG/RECEIVED_SECURITY_LOG_DATA_ERROR';
export const RECEIVED_SECURITY_LOG_DATA_ACTION = 'app/USER_MANAGEMENT/SECURITY_LOG/RECEIVED_SECURITY_LOG_DATA_ACTION';
export const VIEW_SECURITY_LOG_ACTION  = 'app/USER_MANAGEMENT/SECURITY_LOG/VIEW_SECURITY_LOG_ACTION';

export const GET_SECURITY_LOG_DATA = 'app/USER_MANAGEMENT/SECURITY_LOG/GET_SECURITY_LOG_DATA';
export const RESET_TASK_ACTION = 'app/USER_MANAGEMENT/SECURITY_LOG/RESET_TASK_ACTION';

export const REGISTER_ACTION = 'app/USER_MANAGEMENT/SECURITY_LOG/REGISTER_ACLOGIN_ACTIONTION';
export const WARNING_BACK_ACTION = 'app/USER_MANAGEMENT/SECURITY_LOG/WARNING_BACK_ACTION';