
export const MOVE_TO_URL_ACTION = 'app/MerchantAddStep1/MOVE_TO_URL_ACTION';
export const SAVE_MERCHANT_ACTION = 'app/MerchantAddStep1/SAVE_MERCHANT_ACTION';
export const HANDLE_ITEM_CHANGE_ACTION = 'app/MerchantAddStep1/HANDLE_ITEM_CHANGE_ACTION';
export const RESET_TASK_ACTION = 'app/MerchantAddStep1/RESET_TASK_ACTION';
export const RECEIVED_MERCHANT_DATA_ACTION = 'app/MerchantAddStep1/RECEIVED_MERCHANT_DATA_ACTION';
export const RECEIVED_MERCHANTS_DATA_ERROR = 'app/MerchantAddStep1/RECEIVED_MERCHANTS_DATA_ERROR';
export const HANDLE_AUTO_COMPLETE_CHANGE_ACTION = 'app/MerchantAddStep1/HANDLE_AUTO_COMPLETE_CHANGE_ACTION';
