export const DEFAULT_ACTION = 'app/MERCHANT/MAINTAIN/MANAGE_USER/DEFAULT_ACTION';
export const SUBMIT_FORM = 'app/MERCHANT/MAINTAIN/MANAGE_USER/SUBMIT_FORM';
export const MOVE_TO_URL_ACTION = 'app/MERCHANT/MAINTAIN/MANAGE_USER/MOVE_TO_URL_ACTION';

export const HANDLE_ITEM_CHANGE_ACTION = 'app/MERCHANT/MAINTAIN/MANAGE_USER/HANDLE_ITEM_CHANGE_ACTION';
export const HANDLE_PERMISSION_ITEM_CHANGE_ACTION = 'app/MERCHANT/MAINTAIN/MANAGE_USER/HANDLE_PERMISSION_ITEM_CHANGE_ACTION';

export const RECEIVED_USER_SEARCH_DATA_ERROR = 'app/MERCHANT/MAINTAIN/MANAGE_USER/RECEIVED_USER_SEARCH_DATA_ERROR';
export const RECEIVED_USER_SEARCH_DATA_ACTION = 'app/MERCHANT/MAINTAIN/MANAGE_USER/RECEIVED_USER_SEARCH_DATA_ACTION';
export const VIEW_USER_ACTION  = 'app/MERCHANT/MAINTAIN/MANAGE_USER/VIEW_USER_ACTION';

export const RECEIVED_USER_DATA_ACTION  = 'app/MERCHANT/MAINTAIN/MANAGE_USER/RECEIVED_USER_DATA_ACTION';
export const RECEIVED_USER_DATA_ERROR  = 'app/MERCHANT/MAINTAIN/MANAGE_USER/RECEIVED_USER_DATA_ERROR';
export const RECEIVED_USER_LIST_DATA_ACTION  = 'app/MERCHANT/MAINTAIN/MANAGE_USER/RECEIVED_USER_LIST_DATA_ACTION';
export const RECEIVED_USER_LIST_DATA_ERROR  = 'app/MERCHANT/MAINTAIN/MANAGE_USER/RECEIVED_USER_LIST_DATA_ERROR';

export const RECEIVED_FORM_SUBMISSION = 'app/MERCHANT/MAINTAIN/MANAGE_USER/RECEIVED_FORM_SUBMISSION';

 
export const GET_USER_SEARCH_DATA = 'app/MERCHANT/MAINTAIN/MANAGE_USER/GET_USER_SEARCH_DATA';
export const GET_MERCHANT_SEARCH_DATA = 'app/MERCHANT/MAINTAIN/MANAGE_USER/GET_MERCHANT_SEARCH_DATA';
export const CHANGE_PAGE_ACTION = 'app/MERCHANT/MAINTAIN/MANAGE_USER/CHANGE_PAGE_ACTION';

export const RESET_TASK_ACTION = 'app/MERCHANT/MAINTAIN/MANAGE_USER/RESET_TASK_ACTION';

export const RECEIVED_SUBMISSION_ACTION = 'app/MERCHANT/MAINTAIN/MANAGE_USER/RECEIVED_SUBMISSION_ACTION';
export const GET_USER_LIST_DATA = 'app/MERCHANT/MAINTAIN/MANAGE_USER/GET_USER_LIST_DATA';
export const ADD_USER_ACTION = 'app/MERCHANT/MAINTAIN/MANAGE_USER/ADD_USER_ACTION';

export const DELETE_USER_ACTION = 'app/MERCHANT/MAINTAIN/MANAGE_USER/DELETE_USER_ACTION';
export const RECEIVED_USER_DELETE_ACTION = 'app/MERCHANT/MAINTAIN/MANAGE_USER/RECEIVED_USER_DELETE_ACTION';
export const RECEIVED_USER_DELETE_ERROR = 'app/MERCHANT/MAINTAIN/MANAGE_USER/RECEIVED_USER_DELETE_ERROR';

export const REGISTER_FROM_LOCATION = 'app/MERCHANT/MAINTAIN/MANAGE_USER/RECEIVED_USER_DELETE_ERROR';

export const OPEN_USER_MERCHANT_ACCESS = 'app/MERCHANT/MAINTAIN/MANAGE_USER/OPEN_USER_MERCHANT_ACCESS';
export const CLOSE_USER_MERCHANT_ACCESS = 'app/MERCHANT/MAINTAIN/MANAGE_USER/CLOSE_USER_MERCHANT_ACCESS';

export const ENABLE_USER_ACCESS_ACTION = 'app/MERCHANT/MAINTAIN/MANAGE_USER/ENABLE_USER_ACCESS_ACTION';
export const RECEIVED_ENABLE_USER_ACCESS_ACTION = 'app/MERCHANT/MAINTAIN/MANAGE_USER/RECEIVED_ENABLE_USER_ACCESS_ACTION';
export const RECEIVED_ENABLE_USER_ACCESS_ERROR = 'app/MERCHANT/MAINTAIN/MANAGE_USER/ENABLE_USER_ACCESS_ERROR';

export const DELETE_USER_ACCESS_ACTION = 'app/MERCHANT/MAINTAIN/MANAGE_USER/DELETE_USER_ACCESS_ACTION';
export const RECEIVED_DELETE_USER_ACCESS_ACTION = 'app/MERCHANT/MAINTAIN/MANAGE_USER/RECEIVED_ENABLE_USER_ACCESS_ACTION';
export const RECEIVED_DELETE_USER_ACCESS_ERROR = 'app/MERCHANT/MAINTAIN/MANAGE_USER/RECEIVED_DELETE_USER_ACCESS_ERROR';
export const HANDLE_MERCHANT_SEARCH_ITEM_CHANGE_ACTION = 'app/MERCHANT/MAINTAIN/MANAGE_USER/HANDLE_MERCHANT_SEARCH_ITEM_CHANGE_ACTION';

export const CLEAR_USER_ACTION = 'app/MERCHANT/MAINTAIN/MANAGE_USER/CLEAR_USER_ACTION';

export const RECEIVED_MERCHANT_SEARCH_DATA_ACTION = 'app/MERCHANT/MAINTAIN/MANAGE_USER/RECEIVED_MERCHANT_SEARCH_DATA_ACTION';
export const RECEIVED_MERCHANT_SEARCH_DATA_ERROR = 'app/MERCHANT/MAINTAIN/MANAGE_USER/CLEARRECEIVED_MERCHANT_SEARCH_DATA_ERROR_USER_ACTION';


 