/*
 *
 * MerchantAddStep4 constants
 *
 */


export const MOVE_TO_URL_ACTION = 'app/MerchantAddStep4/MOVE_TO_URL_ACTION';
export const ADD_MERCHANT_STEP4_ACTION = 'app/MerchantAddStep4/ADD_MERCHANT_STEP4_ACTION';
export const SAVE_LOCATION = 'app/MerchantAddStep4/SAVE_LOCATION';
export const LOCATION_SAVED = 'app/MerchantAddStep4/LOCATION_SAVED';
export const HANDLE_ITEM_CHANGE_ACTION = 'app/MerchantAddStep4/HANDLE_ITEM_CHANGE_ACTION';
export const HANDLE_FILE_CHANGE_ACTION = 'app/MerchantAddStep4/HANDLE_FILE_CHANGE_ACTION';
export const HANDLE_DATE_CHANGE_ACTION = 'app/MerchantAddStep4/HANDLE_DATE_CHANGE_ACTION';
export const HANDLE_MULTISELECT_CHANGE_ACTION = 'app/MerchantAddStep4/HANDLE_MULTISELECT_CHANGE_ACTION';
export const PERFORM_RETURN_ACTION = 'app/MerchantAddStep4/PERFORM_RETURN_ACTION';
export const HANDLE_ACTIVE_TAB_ACTION = 'app/MerchantAddStep4/HANDLE_ACTIVE_TAB_ACTION';
export const RESET_TASK_ACTION = 'app/MerchantAddStep4/RESET_TASK_ACTION';
export const RECEIVED_MERCHANT_DATA_ACTION = 'app/MerchantAddStep4/RECEIVED_MERCHANT_DATA_ACTION';
export const RECEIVED_MERCHANTS_DATA_ERROR = 'app/MerchantAddStep4/RECEIVED_MERCHANTS_DATA_ERROR';
export const WARNING_BACK_ACTION = 'app/MerchantAddStep4/WARNING_BACK_ACTION';
export const HANDLE_DOCUMENT_UPLOAD_ACTION = 'app/MerchantAddStep4/HANDLE_DOCUMENT_UPLOAD_ACTION';
export const RECEIVED_UPLOAD_DOCUMENTS_DATA_ACTION = 'app/MerchantAddStep4/RECEIVED_UPLOAD_DOCUMENTS_DATA_ACTION';
