export const DEFAULT_ACTION = 'app/RISK/MERCHANT_RESERVE/DEFAULT_ACTION';
export const MOVE_TO_URL_ACTION = 'app/RISK/MERCHANT_RESERVE/MOVE_TO_URL_ACTION';

export const GET_MERCHANT_RESERVE = 'app/RISK/MERCHANT_RESERVE/GET_MERCHANT_RESERVE';
export const RECEIVE_MERCHANT_RESERVE = 'app/RISK/MERCHANT_RESERVE/RECEIVE_MERCHANT_RESERVE';
export const RECEIVE_MERCHANT_RESERVE_ERROR = 'app/RISK/MERCHANT_RESERVE/RECEIVE_MERCHANT_RESERVE_ERROR';
export const HANDLE_ITEM_CHANGE_ACTION = 'app/RISK/MERCHANT_RESERVE/HANDLE_ITEM_CHANGE_ACTION';

