export const DEFAULT_ACTION = 'app/USER_MANAGEMENT/MANAGE_USER/DEFAULT_ACTION';
export const SUBMIT_FORM = 'app/USER_MANAGEMENT/MANAGE_USER/SUBMIT_FORM';
export const MOVE_TO_URL_ACTION = 'app/USER_MANAGEMENT/MANAGE_USER/MOVE_TO_URL_ACTION';

export const HANDLE_ITEM_CHANGE_ACTION = 'app/USER_MANAGEMENT/MANAGE_USER/HANDLE_ITEM_CHANGE_ACTION';
export const HANDLE_PERMISSION_ITEM_CHANGE_ACTION = 'app/USER_MANAGEMENT/MANAGE_USER/HANDLE_PERMISSION_ITEM_CHANGE_ACTION';

export const RECEIVED_USER_SEARCH_DATA_ERROR = 'app/USER_MANAGEMENT/MANAGE_USER/RECEIVED_USER_SEARCH_DATA_ERROR';
export const RECEIVED_USER_SEARCH_DATA_ACTION = 'app/USER_MANAGEMENT/MANAGE_USER/RECEIVED_USER_SEARCH_DATA_ACTION';
export const VIEW_USER_ACTION  = 'app/USER_MANAGEMENT/MANAGE_USER/VIEW_USER_ACTION';

export const RECEIVED_USER_DATA_ACTION  = 'app/USER_MANAGEMENT/MANAGE_USER/RECEIVED_USER_DATA_ACTION';
export const RECEIVED_USER_DATA_ERROR  = 'app/USER_MANAGEMENT/MANAGE_USER/RECEIVED_USER_DATA_ERROR';
export const RECEIVED_USER_LIST_DATA_ACTION  = 'app/USER_MANAGEMENT/MANAGE_USER/RECEIVED_USER_LIST_DATA_ACTION';
export const RECEIVED_USER_LIST_DATA_ERROR  = 'app/USER_MANAGEMENT/MANAGE_USER/RECEIVED_USER_LIST_DATA_ERROR';

export const RECEIVED_FORM_SUBMISSION = 'app/USER_MANAGEMENT/MANAGE_USER/RECEIVED_FORM_SUBMISSION';

 
export const GET_USER_SEARCH_DATA = 'app/USER_MANAGEMENT/MANAGE_USER/GET_USER_SEARCH_DATA';
export const RESET_TASK_ACTION = 'app/USER_MANAGEMENT/MANAGE_USER/RESET_TASK_ACTION';

export const RECEIVED_SUBMISSION_ACTION = 'app/USER_MANAGEMENT/MANAGE_USER/RECEIVED_SUBMISSION_ACTION';
export const GET_USER_LIST_DATA = 'app/USER_MANAGEMENT/MANAGE_USER/GET_USER_LIST_DATA';
export const ADD_USER_ACTION = 'app/USER_MANAGEMENT/MANAGE_USER/ADD_USER_ACTION';

export const DELETE_USER_ACTION = 'app/USER_MANAGEMENT/MANAGE_USER/DELETE_USER_ACTION';
export const RECEIVED_USER_DELETE_ACTION = 'app/USER_MANAGEMENT/MANAGE_USER/RECEIVED_USER_DELETE_ACTION';
export const RECEIVED_USER_DELETE_ERROR = 'app/USER_MANAGEMENT/MANAGE_USER/RECEIVED_USER_DELETE_ERROR';

export const REGISTER_FROM_LOCATION = 'app/USER_MANAGEMENT/MANAGE_USER/RECEIVED_USER_DELETE_ERROR';
export const CLEAR_USER_ACTION = 'app/USER_MANAGEMENT/MANAGE_USER/CLEAR_USER_ACTION';




 