export const DEFAULT_ACTION = 'app/ISO_LIST_DASHBOARD/DEFAULT_ACTION';
export const GET_ISO_MERCHANT_DASHBOARD_DATA = 'app/ISO_LIST_DASHBOARD/GET_ISO_MERCHANT_DASHBOARD_DATA';
export const MOVE_TO_URL_ACTION = 'app/ISO_LIST_DASHBOARD/MOVE_TO_URL_ACTION';

export const RECEIVED_ISO_DASHBOARD_DATA_ERROR = 'app/ISO_LIST_DASHBOARD/RECEIVED_ISO_DASHBOARD_DATA_ERROR';
export const RECEIVED_ISO_DASHBOARD_DATA_ACTION = 'app/ISO_LIST_DASHBOARD/RECEIVED_ISO_DASHBOARD_DATA_ACTION';

export const RECEIVED_ISO_MERCHANT_COUNT_DATA_ERROR = 'app/ISO_LIST_DASHBOARD/RECEIVED_ISO_MERCHANT_COUNT_DATA_ERROR';
export const RECEIVED_ISO_MERCHANT_COUNT_DATA_ACTION = 'app/ISO_LIST_DASHBOARD/RECEIVED_ISO_MERCHANT_COUNT_DATA_ACTION';
export const GET_ISO_MERCHANT_COUNT_DATA = 'app/ISO_LIST_DASHBOARD/GET_ISO_MERCHANT_COUNT_DATA';

export const GET_ISO_DASHBOARD_DATA = 'app/ISO_LIST_DASHBOARD/GET_ISO_DASHBOARD_DATA';
export const RESET_TASK_ACTION = 'app/ISO_LIST_DASHBOARD/RESET_TASK_ACTION';

export const VIEW_MERCHANT_DETAIL_ACTION = 'app/ISO_LIST_DASHBOARD/VIEW_MERCHANT_DETAIL_ACTION';
export const GET_ISO_ISO_DASHBOARD_DATA = 'app/ISO_LIST_DASHBOARD/GET_ISO_ISO_DASHBOARD_DATA';
export const VIEW_ISO_DETAIL_ACTION = 'app/ISO_LIST_DASHBOARD/VIEW_ISO_DETAIL_ACTION';

