/*
 *
 * DASISODashboard constants
 *
 */

export const DEFAULT_ACTION = 'app/DASISODashboard/DEFAULT_ACTION';
export const DISPLAY_WARNING_ACTION = 'app/DASISODashboard/DISPLAY_WARNING_ACTION';
export const MOVE_TO_URL_ACTION = 'app/DASISODashboard/MOVE_TO_URL_ACTION';

export const SUBMIT_LOGIN_ACTION = 'app/DASISODashboard/SUBMIT_LOGIN_ACTION';
export const RECEIVED_DASHBOARD_DATA_ERROR = 'app/DASISODashboard/RECEIVED_DASHBOARD_DATA_ERROR';
export const RECEIVED_DASHBOARD_DATA_ACTION = 'app/DASISODashboard/RECEIVED_DASHBOARD_DATA_ACTION';

export const GET_DASHBOARD_DATA = 'app/DASISODashboard/GET_DASHBOARD_DATA';
export const RESET_TASK_ACTION = 'app/DASISODashboard/RESET_TASK_ACTION';

export const REGISTER_ACTION = 'app/DASISODashboard/REGISTER_ACLOGIN_ACTIONTION';
export const WARNING_BACK_ACTION = 'app/DASISODashboard/WARNING_BACK_ACTION';
export const EXIT_ACTION = 'app/DASISODashboard/EXIT_ACTION';
export const LOGIN_ACTION = 'app/DASISODashboard/LOGIN_ACTION';
export const FORGOT_PASSWORD_ACTION = 'app/DASISODashboard/FORGOT_PASSWORD_ACTION';
export const REGISTER_VERIFY_ACTION = 'app/DASISODashboard/REGISTER_VERIFY_ACTION';






