export const DEFAULT_ACTION = 'app/Dashboard/DEFAULT_ACTION';
export const DISPLAY_WARNING_ACTION = 'app/Dashboard/DISPLAY_WARNING_ACTION';
export const MOVE_TO_URL_ACTION = 'app/Dashboard/MOVE_TO_URL_ACTION';

export const SUBMIT_LOGIN_ACTION = 'app/Dashboard/SUBMIT_LOGIN_ACTION';
export const RECEIVED_DASHBOARD_DATA_ERROR = 'app/Dashboard/RECEIVED_DASHBOARD_DATA_ERROR';
export const RECEIVED_DASHBOARD_DATA_ACTION = 'app/Dashboard/RECEIVED_DASHBOARD_DATA_ACTION';

export const GET_DASHBOARD_DATA = 'app/Dashboard/GET_DASHBOARD_DATA';
export const RESET_TASK_ACTION = 'app/Dashboard/RESET_TASK_ACTION';

export const GET_MERCHANT_DETAIL_ACTION = 'app/Dashboard/GET_MERCHANT_DETAIL_ACTION';
export const VIEW_ISO_DETAIL_ACTION = 'app/Dashboard/VIEW_ISO_DETAIL_ACTION';
export const HANDLE_MERCHANT_SEARCH_ITEM_CHANGE_ACTION = 'app/Dashboard/HANDLE_MERCHANT_SEARCH_ITEM_CHANGE_ACTION';
export const OPEN_MERCHANT_LIST_ACTION = 'app/Dashboard/OPEN_MERCHANT_LIST_ACTION';
export const CLOSE_MERCHANT_LIST_ACTION = 'app/Dashboard/CLOSE_MERCHANT_LIST_ACTION';
export const SELECT_MERCHANT_ACTION = 'app/Dashboard/SELECT_MERCHANT_ACTION';



