export const DEFAULT_ACTION = 'app/MerchantDetail/DEFAULT_ACTION';
export const MOVE_TO_URL_ACTION = 'app/MerchantDetail/MOVE_TO_URL_ACTION';

export const HANDLE_ITEM_CHANGE_ACTION = 'app/MerchantDetail/HANDLE_ITEM_CHANGE_ACTION';
export const RECEIVED_MERCHANT_DETAIL_DATA_ERROR = 'app/MerchantDetail/RECEIVED_MERCHANT_DETAIL_DATA_ERROR';
export const RECEIVED_MERCHANT_DETAIL_DATA_ACTION = 'app/MerchantDetail/RECEIVED_MERCHANT_DETAIL_DATA_ACTION';
export const VIEW_MERCHANT_ACTION  = 'app/MerchantDetail/VIEW_MERCHANT_ACTION';

export const GET_MERCHANT_DETAIL_DATA = 'app/MerchantDetail/GET_MERCHANT_DETAIL_DATA';
export const RESET_TASK_ACTION = 'app/MerchantDetail/RESET_TASK_ACTION';
export const GET_MERCHANT_ACTION = 'app/MerchantDetail/GET_MERCHANT_ACTION';


export const RECEIVED_PAGE_CHANGE_ERROR = 'app/MerchantDetail/RECEIVED_PAGE_CHANGE_ERROR';
export const RECEIVED_PAGE_CHANGE_ACTION = 'app/MerchantDetail/RECEIVED_PAGE_CHANGE_ACTION';
export const CHANGE_PAGE_ACTION = 'app/MerchantDetail/CHANGE_PAGE_ACTION';

export const VIEW_TRANSACTION_DETAIL = 'app/MerchantDetail/VIEW_TRANSACTION_DETAIL';
export const VIEW_BATCH_DETAIL = 'app/MerchantDetail/VIEW_BATCH_DETAIL';
export const VIEW_ACH_DETAIL = 'app/MerchantDetail/VIEW_ACH_DETAIL';
export const VIEW_CHARGEBACK_DETAIL = 'app/MerchantDetail/VIEW_CHARGEBACK_DETAIL';

export const CLOSE_TRANSACTION_DETAIL = 'app/MerchantDetail/CLOSE_TRANSACTION_DETAIL';
export const CLOSE_BATCH_DETAIL = 'app/MerchantDetail/CLOSE_BATCH_DETAIL';
export const CLOSE_ACH_DETAIL = 'app/MerchantDetail/CLOSE_ACH_DETAIL';
export const CLOSE_CHARGEBACK_DETAIL = 'app/MerchantDetail/CLOSE_CHARGEBACK_DETAIL';

export const HANDLE_SEARCH_CHANGE_ACTION = 'app/MerchantDetail/HANDLE_SEARCH_CHANGE_ACTION';
export const RECEIVED_CHARGE_BACK_EXPORT_ACTION = 'app/MerchantDetail/RECEIVED_CHARGE_BACK_EXPORT_ACTION';
export const EXPORT_CHARGE_BACK_ACTION = 'app/MerchantDetail/EXPORT_CHARGE_BACK_ACTIONV';
export const RECEIVED_CHARGE_BACK_EXPORT_ERROR = 'app/MerchantDetail/RECEIVED_CHARGE_BACK_EXPORT_ERROR';

export const GET_STATEMENT_ACTION = 'app/MerchantDetail/GET_STATEMENT_ACTION';
export const RECEIVED_STATEMENT_ACTION = 'app/MerchantDetail/RECEIVED_STATEMENT_ACTION';
export const RECEIVED_STATEMENT_ERROR = 'app/MerchantDetail/RECEIVED_STATEMENT_ERROR';

 