
export const DEFAULT_ACTION = 'app/PasswordReset/DEFAULT_ACTION';
export const SUBMIT_PASSWORD_RESET_INFO_ACTION = 'app/PasswordReset/SUBMIT_PASSWORD_RESET_INFO_ACTION';
export const MOVE_TO_URL_ACTION = 'app/PasswordReset/MOVE_TO_URL_ACTION';
export const RESET_TASK_ACTION = 'app/PasswordReset/RESET_TASK_ACTION';
export const HANDLE_PASSWORD_RESET_ITEM_CHANGE_ACTION = 'app/PasswordReset/HANDLE_PASSWORD_RESET_ITEM_CHANGE_ACTION';
export const RECEIVE_PASSWORD_RESET_ACTION = 'app/PasswordReset/RECEIVE_PASSWORD_RESET_ACTION';
export const RECEIVE_PASSWORD_RESET_ERROR = 'app/PasswordReset/RECEIVE_PASSWORD_RESET_ERROR';
export const RECEIVE_PASSWORD_RESET_DISPLAY_ERROR = 'app/PasswordReset/RECEIVE_PASSWORD_RESET_DISPLAY_ERROR';
export const RECEIVE_PASSWORD_RESET_DISPLAY_ACTION = 'app/PasswordReset/RECEIVE_PASSWORD_RESET_DISPLAY_ACTION';
