export const DEFAULT_ACTION = 'app/Login/DEFAULT_ACTION';
export const DISPLAY_WARNING_ACTION = 'app/Login/DISPLAY_WARNING_ACTION';
export const MOVE_TO_URL_ACTION = 'app/Login/MOVE_TO_URL_ACTION';

export const SUBMIT_LOGIN_ACTION = 'app/Login/SUBMIT_LOGIN_ACTION';
export const SUBMITTED_LOGIN_INFO_ERROR = 'app/Login/SUBMITTED_LOGIN_INFO_ERROR';
export const RECEIVED_LOGIN_INFO_ACTION = 'app/Login/RECEIVED_LOGIN_INFO_ACTION';

export const HANDLE_LOGIN_INFO_CHANGE_ACTION = 'app/Login/HANDLE_LOGIN_INFO_CHANGE_ACTION';
export const RESET_TASK_ACTION = 'app/Login/RESET_TASK_ACTION';

export const REGISTER_ACTION = 'app/Login/REGISTER_ACLOGIN_ACTIONTION';
export const WARNING_BACK_ACTION = 'app/Login/WARNING_BACK_ACTION';
export const EXIT_ACTION = 'app/Login/EXIT_ACTION';
export const LOGIN_ACTION = 'app/Login/LOGIN_ACTION';
export const FORGOT_PASSWORD_ACTION = 'app/Login/FORGOT_PASSWORD_ACTION';
export const REGISTER_VERIFY_ACTION = 'app/Login/REGISTER_VERIFY_ACTION';
